# Site
name: 'Ulfhednar Miniatures'
description: 'Where paint meets plastic... sometimes.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/apple-touch-icon-180x180-precomposed.png'
irl: 'https://ulfhednar-asn.github.io'
baseurl: '/'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Ulfhednar
      site:           https://ulfhednar-asn.github.io
      avatar:         /assets/images/touch-icon-192x192.png
      bio:            "Master procrastinator, kitbasher and occasional miniature painter."

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]